CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211002107_FinalSchemaV2') THEN
    CREATE TABLE "Reservations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "GuestName" text NOT NULL,
        "RoomId" integer NOT NULL,
        "CheckInDate" timestamp with time zone NOT NULL,
        "CheckOutDate" timestamp with time zone NOT NULL,
        "Status" text NOT NULL,
        "TotalPrice" numeric(18,2) NOT NULL,
        "IsPaid" boolean NOT NULL,
        CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211002107_FinalSchemaV2') THEN
    CREATE TABLE "Rooms" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Number" text NOT NULL,
        "Type" text NOT NULL,
        "Status" text NOT NULL,
        "Price" numeric(18,2) NOT NULL,
        "Capacity" integer NOT NULL,
        "IsOccupied" boolean NOT NULL,
        CONSTRAINT "PK_Rooms" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251211002107_FinalSchemaV2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251211002107_FinalSchemaV2', '10.0.1');
    END IF;
END $EF$;
COMMIT;

